import { Workflow, Category, Author } from "@/types/workflow";

export const categories: Category[] = [
  {
    id: "data-sync",
    name: "数据同步",
    slug: "data-sync",
    icon: "📊",
    description: "跨平台数据同步和备份解决方案",
    count: 128,
    color: "#3B82F6",
  },
  {
    id: "automation",
    name: "自动化",
    slug: "automation",
    icon: "🔄",
    description: "日常任务自动化和工作流优化",
    count: 256,
    color: "#10B981",
  },
  {
    id: "email-marketing",
    name: "邮件营销",
    slug: "email-marketing",
    icon: "📧",
    description: "邮件营销自动化和客户关系管理",
    count: 89,
    color: "#F59E0B",
  },
  {
    id: "crm",
    name: "CRM集成",
    slug: "crm",
    icon: "💼",
    description: "CRM系统与其他工具的集成方案",
    count: 167,
    color: "#8B5CF6",
  },
  {
    id: "customer-service",
    name: "客户服务",
    slug: "customer-service",
    icon: "💬",
    description: "客服系统自动化和工单管理",
    count: 76,
    color: "#EC4899",
  },
  {
    id: "social-media",
    name: "社交媒体",
    slug: "social-media",
    icon: "📱",
    description: "社交媒体内容发布和监控",
    count: 94,
    color: "#06B6D4",
  },
  {
    id: "design",
    name: "设计协作",
    slug: "design",
    icon: "🎨",
    description: "设计工具协作和资产管理",
    count: 52,
    color: "#F97316",
  },
  {
    id: "security",
    name: "安全监控",
    slug: "security",
    icon: "🔐",
    description: "安全监控、告警和合规检查",
    count: 38,
    color: "#EF4444",
  },
];

export const authors: Author[] = [
  {
    id: "author-1",
    name: "张伟",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
    bio: "N8N认证专家，5年自动化经验",
    website: "https://github.com/zhangwei",
    workflows: 23,
    rating: 4.9,
  },
  {
    id: "author-2",
    name: "李娜",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka",
    bio: "企业自动化顾问",
    website: "https://github.com/lina",
    workflows: 18,
    rating: 4.8,
  },
  {
    id: "author-3",
    name: "王强",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    bio: "全栈开发者，N8N社区贡献者",
    website: "https://github.com/wangqiang",
    workflows: 31,
    rating: 5.0,
  },
];

export const workflows: Workflow[] = [
  {
    id: "wf-1",
    title: "Slack实时通知自动化",
    slug: "slack-notification-automation",
    description: "自动将重要事件和更新发送到Slack频道，支持自定义触发条件和消息格式。",
    longDescription:
      "这个强大的工作流可以自动将各种重要事件发送到您的Slack频道。支持自定义触发条件、富文本消息格式、多频道同时发送以及错误重试机制。非常适合团队协作和监控告警场景。",
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
    category: "automation",
    tags: ["slack", "通知", "自动化", "团队协作"],
    rating: 4.9,
    downloads: 2345,
    isFree: false,
    price: 29,
    originalPrice: 49,
    author: authors[0],
    features: [
      "自定义触发条件",
      "富文本消息格式",
      "多频道同时发送",
      "错误重试机制",
      "支持变量和表达式",
      "定时发送功能",
    ],
    requirements: ["N8N 1.0+", "Slack API Token", "Node.js 18+"],
    version: "2.1.0",
    updatedAt: "2025-01-05",
    createdAt: "2024-10-15",
    difficulty: "beginner",
    platform: ["Slack", "Webhook", "HTTP"],
    language: "中文",
    screenshots: [
      "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=800&fit=crop",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    documentation: "https://docs.example.com/slack-automation",
    license: "MIT",
  },
  {
    id: "wf-2",
    title: "邮件营销自动化系统",
    slug: "email-marketing-automation",
    description: "完整的邮件营销自动化解决方案，包含用户分段、邮件序列和效果追踪。",
    longDescription:
      "这是一个企业级的邮件营销自动化系统。包含用户自动分段、个性化邮件序列、A/B测试、发送时间优化、打开率和点击率追踪等功能。可以大幅提升邮件营销的转化率和ROI。",
    thumbnail: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=600&fit=crop",
    category: "email-marketing",
    tags: ["邮件", "营销", "自动化", "CRM"],
    rating: 4.8,
    downloads: 1892,
    isFree: false,
    price: 79,
    originalPrice: 129,
    author: authors[1],
    features: [
      "智能用户分段",
      "个性化邮件序列",
      "A/B测试功能",
      "最优发送时间预测",
      "详细的营销数据分析",
      "与主流CRM集成",
    ],
    requirements: ["N8N 1.2+", "SMTP配置", "数据库"],
    version: "3.0.1",
    updatedAt: "2025-01-03",
    createdAt: "2024-09-20",
    difficulty: "intermediate",
    platform: ["Gmail", "SendGrid", "Mailchimp"],
    language: "中文",
    license: "Proprietary",
  },
  {
    id: "wf-3",
    title: "CRM数据同步工作流",
    slug: "crm-data-sync",
    description: "自动同步多个CRM系统之间的数据，保持客户信息一致性和实时更新。",
    longDescription:
      "这个工作流可以自动在多个CRM系统之间同步客户数据，确保所有系统的数据保持一致。支持双向同步、冲突解决策略、数据验证和清洗、增量同步等功能。",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
    category: "crm",
    tags: ["CRM", "数据同步", "集成", "Salesforce"],
    rating: 5.0,
    downloads: 3156,
    isFree: false,
    price: 49,
    originalPrice: 89,
    author: authors[2],
    features: [
      "多CRM系统支持",
      "双向数据同步",
      "智能冲突解决",
      "数据验证和清洗",
      "增量同步优化",
      "详细的同步日志",
    ],
    requirements: ["N8N 1.1+", "CRM API访问权限"],
    version: "1.8.0",
    updatedAt: "2025-01-04",
    createdAt: "2024-08-10",
    difficulty: "advanced",
    platform: ["Salesforce", "HubSpot", "Zoho"],
    language: "中文",
    license: "Apache-2.0",
  },
  {
    id: "wf-4",
    title: "微信公众号内容采集",
    slug: "wechat-content-scraper",
    description: "自动采集微信公众号文章，支持内容治理和站外分发。",
    longDescription:
      "这个工作流可以自动采集指定的微信公众号文章，包括文章内容、图片、阅读数、点赞数等信息。支持内容过滤、格式转换、自动分类和多平台分发功能。",
    thumbnail: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=600&fit=crop",
    category: "data-sync",
    tags: ["微信", "内容采集", "自动化", "营销"],
    rating: 4.7,
    downloads: 986,
    isFree: true,
    author: authors[0],
    features: [
      "批量公众号采集",
      "文章内容完整提取",
      "图片自动下载",
      "数据格式标准化",
      "自动去重功能",
    ],
    requirements: ["N8N 1.0+", "微信公众号账号"],
    version: "1.2.0",
    updatedAt: "2024-12-28",
    createdAt: "2024-07-05",
    difficulty: "intermediate",
    platform: ["WeChat", "Webhook"],
    language: "中文",
    license: "MIT",
  },
  {
    id: "wf-5",
    title: "社交媒体内容日历",
    slug: "social-media-calendar",
    description: "自动管理和发布社交媒体内容，支持多平台和定时发布。",
    longDescription:
      "这个工作流帮助您管理社交媒体内容日历，支持一键发布到多个社交平台。包含内容审核、定时发布、互动追踪、数据分析等功能，是社交媒体营销的得力助手。",
    thumbnail: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=800&h=600&fit=crop",
    category: "social-media",
    tags: ["社交媒体", "内容营销", "定时发布"],
    rating: 4.6,
    downloads: 1543,
    isFree: false,
    price: 39,
    originalPrice: 69,
    author: authors[1],
    features: [
      "多平台一键发布",
      "智能内容日历",
      "最佳发布时间建议",
      "互动数据分析",
      "团队协作功能",
      "内容审核流程",
    ],
    requirements: ["N8N 1.1+", "社交媒体API"],
    version: "2.0.3",
    updatedAt: "2025-01-02",
    createdAt: "2024-09-01",
    difficulty: "beginner",
    platform: ["Twitter", "LinkedIn", "Facebook", "Instagram"],
    language: "中文",
    license: "Proprietary",
  },
  {
    id: "wf-6",
    title: "客服工单自动路由",
    slug: "ticket-auto-routing",
    description: "智能路由客服工单到合适的客服人员，提升响应速度和客户满意度。",
    longDescription:
      "这个工作流可以自动分析客服工单的内容和紧急程度，并将其路由到最合适的客服人员。支持基于技能、工作负载、历史表现等多种路由策略，大幅提升客服效率。",
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
    category: "customer-service",
    tags: ["客服", "工单", "自动化", "AI"],
    rating: 4.9,
    downloads: 1234,
    isFree: false,
    price: 59,
    originalPrice: 99,
    author: authors[2],
    features: [
      "AI智能分类",
      "多维度路由策略",
      "紧急程度评估",
      "工作量均衡",
      "SLA监控",
      "自动升级机制",
    ],
    requirements: ["N8N 1.2+", "客服系统API"],
    version: "1.5.0",
    updatedAt: "2024-12-30",
    createdAt: "2024-06-15",
    difficulty: "advanced",
    platform: ["Zendesk", "Freshdesk", "Intercom"],
    language: "中文",
    license: "GPL-3.0",
  },
  {
    id: "wf-7",
    title: "文件自动备份到云存储",
    slug: "auto-cloud-backup",
    description: "自动监控文件夹变化并备份到多个云存储服务，确保数据安全。",
    longDescription:
      "这个工作流可以自动监控指定文件夹的变化，并将新增或修改的文件自动备份到多个云存储服务。支持增量备份、版本控制、压缩加密和备份报告功能。",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
    category: "data-sync",
    tags: ["备份", "云存储", "自动化", "安全"],
    rating: 4.8,
    downloads: 2156,
    isFree: true,
    author: authors[0],
    features: ["实时文件监控", "多云备份", "增量备份优化", "文件加密", "版本控制", "备份报告"],
    requirements: ["N8N 1.0+", "云存储API"],
    version: "2.3.0",
    updatedAt: "2024-12-25",
    createdAt: "2024-05-20",
    difficulty: "beginner",
    platform: ["Google Drive", "Dropbox", "OneDrive", "AWS S3"],
    language: "中文",
    license: "MIT",
  },
  {
    id: "wf-8",
    title: "设计文件协作工作流",
    slug: "design-collaboration",
    description: "自动同步设计文件、生成预览和通知团队成员，提升设计协作效率。",
    longDescription:
      "这个工作流专为设计团队打造，可以自动同步设计文件到协作平台，生成预览图，通知相关团队成员，并收集反馈。支持Figma、Sketch、Adobe XD等主流设计工具。",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop",
    category: "design",
    tags: ["设计", "协作", "Figma", "自动化"],
    rating: 4.7,
    downloads: 876,
    isFree: false,
    price: 45,
    originalPrice: 75,
    author: authors[1],
    features: [
      "多设计工具支持",
      "自动生成预览",
      "智能版本管理",
      "团队通知",
      "反馈收集",
      "设计资产管理",
    ],
    requirements: ["N8N 1.1+", "设计工具API"],
    version: "1.0.5",
    updatedAt: "2024-12-20",
    createdAt: "2024-08-01",
    difficulty: "intermediate",
    platform: ["Figma", "Sketch", "Adobe XD"],
    language: "中文",
    license: "Proprietary",
  },
  {
    id: "wf-9",
    title: "安全监控和告警系统",
    slug: "security-monitoring",
    description: "实时监控系统安全事件，自动分析威胁并发送告警通知。",
    longDescription:
      "这是一个全面的安全监控和告警系统，可以实时监控各种安全事件，自动分析威胁级别，并采取相应的响应措施。支持多种安全工具集成和自定义告警规则。",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop",
    category: "security",
    tags: ["安全", "监控", "告警", "SIEM"],
    rating: 5.0,
    downloads: 1567,
    isFree: false,
    price: 99,
    originalPrice: 149,
    author: authors[2],
    features: [
      "实时事件监控",
      "AI威胁分析",
      "多级告警策略",
      "自动响应措施",
      "合规报告生成",
      "SIEM系统集成",
    ],
    requirements: ["N8N 1.2+", "安全工具API"],
    version: "3.1.0",
    updatedAt: "2025-01-05",
    createdAt: "2024-07-10",
    difficulty: "advanced",
    platform: ["Splunk", "QRadar", "Azure Sentinel"],
    language: "中文",
    license: "Proprietary",
  },
];

export const featuredWorkflows = workflows.slice(0, 6);
export const freeWorkflows = workflows.filter((w) => w.isFree);
export const paidWorkflows = workflows.filter((w) => !w.isFree);

export function getWorkflowBySlug(slug: string): Workflow | undefined {
  return workflows.find((w) => w.slug === slug);
}

export function getWorkflowById(id: string): Workflow | undefined {
  return workflows.find((w) => w.id === id);
}

export function getWorkflowsByCategory(categorySlug: string): Workflow[] {
  return workflows.filter((w) => w.category === categorySlug);
}

export function searchWorkflows(query: string): Workflow[] {
  const lowerQuery = query.toLowerCase();
  return workflows.filter(
    (w) =>
      w.title.toLowerCase().includes(lowerQuery) ||
      w.description.toLowerCase().includes(lowerQuery) ||
      w.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)),
  );
}

export function getRelatedWorkflows(workflowId: string, limit = 4): Workflow[] {
  const workflow = getWorkflowById(workflowId);
  if (!workflow) return [];

  return workflows
    .filter((w) => w.id !== workflowId && w.category === workflow.category)
    .slice(0, limit);
}
