// 真实开源工作流数据 — 收录自 zengfr/n8n-workflow-all-templates (110★)
// 每条的结构与节点连接均来自仓库真实 workflow JSON
export interface RealWorkflowNode {
  name: string;
  type: string;
}

export interface RealWorkflow {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: string;
  categoryLabel: string;
  nodeCount: number;
  nodes: { name: string; type: string }[];
  flows: string[];
  source: { repo: string; url: string; stars: number };
  author: { name: string; note: string };
  isFree: boolean;
  updatedAt: string;
}

export const realWorkflows: RealWorkflow[] = [
  {"id": "gh-4", "title": "Send selected GitHub events to Slack", "slug": "gh-4-send-selected-github-events-to-slack", "description": "来自 N8N 社区模板库的真实工作流：4 个节点，核心链路 IF → Slack - Add → IF → Slack - Remove。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 4, "nodes": [{"name": "Github Trigger", "type": "githubTrigger"}, {"name": "IF", "type": "if"}, {"name": "Slack - Add", "type": "slack"}, {"name": "Slack - Remove", "type": "slack"}], "flows": ["IF → Slack - Add", "IF → Slack - Remove", "Github Trigger → IF"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/4/4/4_Send_selected_GitHub_events_to_Slack.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-27", "title": "Telegram sticker bot", "slug": "gh-27-telegram-sticker-bot", "description": "来自 N8N 社区模板库的真实工作流：4 个节点，核心链路 Look for Sticker → Return Sticker → Look for Sticker → Return no Sticker found。", "category": "telegram", "categoryLabel": "Telegram 机器人", "nodeCount": 4, "nodes": [{"name": "Telegram Trigger", "type": "telegramTrigger"}, {"name": "Return Sticker", "type": "telegram"}, {"name": "Return no Sticker found", "type": "telegram"}, {"name": "Look for Sticker", "type": "if"}], "flows": ["Look for Sticker → Return Sticker", "Look for Sticker → Return no Sticker found", "Telegram Trigger → Look for Sticker"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/27/27/27_Telegram_sticker_bot.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-29", "title": "Send Typeform results to Google Sheet Slack and email", "slug": "gh-29-send-typeform-results-to-google-sheet-slack-and-email", "description": "来自 N8N 社区模板库的真实工作流：5 个节点，核心链路 IF → Slack → IF → Send Email。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 5, "nodes": [{"name": "Typeform Trigger", "type": "typeformTrigger"}, {"name": "IF", "type": "if"}, {"name": "Google Sheets", "type": "googleSheets"}, {"name": "Send Email", "type": "emailSend"}, {"name": "Slack", "type": "slack"}], "flows": ["IF → Slack", "IF → Send Email", "Google Sheets → IF", "Typeform Trigger → Google Sheets"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/29/29/29_Send_Typeform_results_to_Google_Sheet__Slack_and_email.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-119", "title": "Webhook returning XML", "slug": "gh-119-webhook-returning-xml", "description": "来自 N8N 社区模板库的真实工作流：4 个节点，核心链路 Set → XML → XML → Respond to Webhook。", "category": "automation", "categoryLabel": "通用自动化", "nodeCount": 4, "nodes": [{"name": "XML", "type": "xml"}, {"name": "Set", "type": "set"}, {"name": "Respond to Webhook", "type": "respondToWebhook"}, {"name": "Webhook", "type": "webhook"}], "flows": ["Set → XML", "XML → Respond to Webhook", "Webhook → Set"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/11/11/119_Webhook_returning_XML.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-159", "title": "Send RSS feed data to webhook", "slug": "gh-159-send-rss-feed-data-to-webhook", "description": "来自 N8N 社区模板库的真实工作流：18 个节点，核心链路 IF → End1 → IF → SplitInBatches1。", "category": "content", "categoryLabel": "内容订阅", "nodeCount": 18, "nodes": [{"name": "On clicking 'execute'", "type": "manualTrigger"}, {"name": "Cron", "type": "cron"}, {"name": "RSS Feed Read", "type": "rssFeedRead"}, {"name": "SplitInBatches1", "type": "splitInBatches"}, {"name": "IF", "type": "if"}, {"name": "End1", "type": "noOp"}, {"name": "IF1", "type": "if"}, {"name": "Merge", "type": "merge"}, {"name": "Merge1", "type": "merge"}, {"name": "IF realtors or real estate", "type": "if"}, {"name": "IF restaurant(s)", "type": "if"}, {"name": "SplitInBatches", "type": "splitInBatches"}, {"name": "MongoDB: Find Article", "type": "mongoDb"}, {"name": "MongoDB: Find Article1", "type": "mongoDb"}, {"name": "MongoDB: Insert", "type": "mongoDb"}, {"name": "MongoDB: Insert1", "type": "mongoDb"}, {"name": "Webhook", "type": "httpRequest"}, {"name": "Webhook1", "type": "httpRequest"}], "flows": ["IF → End1", "IF → SplitInBatches1", "IF1 → End1", "IF1 → SplitInBatches", "Cron → RSS Feed Read", "Merge → MongoDB: Insert", "Merge1 → MongoDB: Insert1", "Webhook → IF1", "Webhook1 → IF", "RSS Feed Read → IF realtors or real estate", "SplitInBatches → MongoDB: Find Article", "SplitInBatches → Merge1", "MongoDB: Insert → Webhook1", "SplitInBatches1 → MongoDB: Find Article1", "SplitInBatches1 → Merge", "IF restaurant(s) → SplitInBatches1", "MongoDB: Insert1 → Webhook", "MongoDB: Find Article → Merge1", "On clicking 'execute' → RSS Feed Read", "MongoDB: Find Article1 → Merge", "IF realtors or real estate → SplitInBatches", "IF realtors or real estate → IF restaurant(s)"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/15/15/159_Send_RSS_feed_data_to_webhook.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-199", "title": "RSS Telegram bot", "slug": "gh-199-rss-telegram-bot", "description": "来自 N8N 社区模板库的真实工作流：18 个节点，核心链路 IF → NaN → IF1 → send。", "category": "telegram", "categoryLabel": "Telegram 机器人", "nodeCount": 18, "nodes": [{"name": "SplitInBatches", "type": "splitInBatches"}, {"name": "Function", "type": "function"}, {"name": "Cron1", "type": "cron"}, {"name": "是否重复", "type": "if"}, {"name": "写入图片的属性", "type": "function"}, {"name": "图片数量判断", "type": "if"}, {"name": "一张图片", "type": "telegram"}, {"name": "其他状况", "type": "telegram"}, {"name": "NaN", "type": "function"}, {"name": "SplitInBatches1", "type": "splitInBatches"}, {"name": "Function1", "type": "function"}, {"name": "IF", "type": "if"}, {"name": "IF1", "type": "if"}, {"name": "send", "type": "telegram"}, {"name": "instagram rss", "type": "rssFeedRead"}, {"name": "weibo rss", "type": "rssFeedRead"}, {"name": "Telegram", "type": "telegram"}, {"name": "test", "type": "manualTrigger"}], "flows": ["IF → NaN", "IF1 → send", "IF1 → Telegram", "NaN → IF1", "test → instagram rss", "test → weibo rss", "Cron1 → weibo rss", "Cron1 → instagram rss", "Function → 是否重复", "Function1 → IF", "weibo rss → SplitInBatches", "是否重复 → 写入图片的属性", "instagram rss → SplitInBatches1", "SplitInBatches → Function", "SplitInBatches1 → Function1", "图片数量判断 → 一张图片", "图片数量判断 → 其他状况", "写入图片的属性 → 图片数量判断"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/19/19/199_RSS_Telegram_bot.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-342", "title": "Send daily affirmations to Telegram", "slug": "gh-342-send-daily-affirmations-to-telegram", "description": "来自 N8N 社区模板库的真实工作流：3 个节点，核心链路 Cron → HTTP Request → HTTP Request → Telegram。", "category": "telegram", "categoryLabel": "Telegram 机器人", "nodeCount": 3, "nodes": [{"name": "Cron", "type": "cron"}, {"name": "HTTP Request", "type": "httpRequest"}, {"name": "Telegram", "type": "telegram"}], "flows": ["Cron → HTTP Request", "HTTP Request → Telegram"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/34/34/342_Send_daily_affirmations_to_Telegram.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-346", "title": "Get Weather Forecast via Telegram", "slug": "gh-346-get-weather-forecast-via-telegram", "description": "来自 N8N 社区模板库的真实工作流：3 个节点，核心链路 OpenWeatherMap → Telegram → Telegram Trigger → OpenWeatherMap。", "category": "telegram", "categoryLabel": "Telegram 机器人", "nodeCount": 3, "nodes": [{"name": "Telegram Trigger", "type": "telegramTrigger"}, {"name": "OpenWeatherMap", "type": "openWeatherMap"}, {"name": "Telegram", "type": "telegram"}], "flows": ["OpenWeatherMap → Telegram", "Telegram Trigger → OpenWeatherMap"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/34/34/346_Get_Weather_Forecast_via_Telegram.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-351", "title": "Webhooks with Mattermost", "slug": "gh-351-webhooks-with-mattermost", "description": "来自 N8N 社区模板库的真实工作流：3 个节点，核心链路 Webhook → HTTP Request → HTTP Request → Mattermost。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 3, "nodes": [{"name": "Webhook", "type": "webhook"}, {"name": "HTTP Request", "type": "httpRequest"}, {"name": "Mattermost", "type": "mattermost"}], "flows": ["Webhook → HTTP Request", "HTTP Request → Mattermost"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/35/35/351_Webhooks_with_Mattermost.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-368", "title": "Create ticket on specific customer messages in Telegram", "slug": "gh-368-create-ticket-on-specific-customer-messages-in-telegram", "description": "来自 N8N 社区模板库的真实工作流：8 个节点，核心链路 IF1 → Freshdesk → IF1 → Freshdesk1。", "category": "telegram", "categoryLabel": "Telegram 机器人", "nodeCount": 8, "nodes": [{"name": "Telegram Trigger", "type": "telegramTrigger"}, {"name": "Monday.com", "type": "mondayCom"}, {"name": "Monday.com1", "type": "mondayCom"}, {"name": "Telegram", "type": "telegram"}, {"name": "IF1", "type": "if"}, {"name": "Freshdesk", "type": "freshdesk"}, {"name": "Freshdesk1", "type": "freshdesk"}, {"name": "Telegram1", "type": "telegram"}], "flows": ["IF1 → Freshdesk", "IF1 → Freshdesk1", "Telegram → Monday.com", "Freshdesk → Telegram", "Telegram1 → Monday.com1", "Freshdesk1 → Telegram1", "Telegram Trigger → IF1"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/36/36/368_Create_ticket_on_specific_customer_messages_in_Telegram.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-371", "title": "Notify a team channel about new software releases via Slack and GitHub", "slug": "gh-371-notify-a-team-channel-about-new-software-releases-via-slack-and-github", "description": "来自 N8N 社区模板库的真实工作流：2 个节点，核心链路 Github Trigger → Slack。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 2, "nodes": [{"name": "Slack", "type": "slack"}, {"name": "Github Trigger", "type": "githubTrigger"}], "flows": ["Github Trigger → Slack"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/37/37/371_Notify_a_team_channel_about_new_software_releases_via_Slack_and_GitHub.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-378", "title": "Tiny tiny Rss aka tt-rss Feed to Mastodon", "slug": "gh-378-tiny-tiny-rss-aka-tt-rss-feed-to-mastodon", "description": "来自 N8N 社区模板库的真实工作流：6 个节点，核心链路 IF → HTTP Request → IF → NoOp。", "category": "content", "categoryLabel": "内容订阅", "nodeCount": 6, "nodes": [{"name": "RSS Feed Read", "type": "rssFeedRead"}, {"name": "HTTP Request", "type": "httpRequest"}, {"name": "Cron", "type": "cron"}, {"name": "Function", "type": "function"}, {"name": "IF", "type": "if"}, {"name": "NoOp", "type": "noOp"}], "flows": ["IF → HTTP Request", "IF → NoOp", "Cron → RSS Feed Read", "Function → IF", "RSS Feed Read → Function"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/37/37/378_Tiny_tiny_Rss__aka_tt-rss__Feed_to_Mastodon.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-384", "title": "Save Typeform survey results to Airtable", "slug": "gh-384-save-typeform-survey-results-to-airtable", "description": "来自 N8N 社区模板库的真实工作流：2 个节点，核心链路 Typeform Trigger → Airtable。", "category": "data", "categoryLabel": "数据同步", "nodeCount": 2, "nodes": [{"name": "Typeform Trigger", "type": "typeformTrigger"}, {"name": "Airtable", "type": "airtable"}], "flows": ["Typeform Trigger → Airtable"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/38/38/384_Save_Typeform_survey_results_to_Airtable.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-385", "title": "Send Airtable data as tasks to Trello", "slug": "gh-385-send-airtable-data-as-tasks-to-trello", "description": "来自 N8N 社区模板库的真实工作流：4 个节点，核心链路 Airtable → Bannerbear → Bannerbear → Trello。", "category": "data", "categoryLabel": "数据同步", "nodeCount": 4, "nodes": [{"name": "On clicking 'execute'", "type": "manualTrigger"}, {"name": "Airtable", "type": "airtable"}, {"name": "Bannerbear", "type": "bannerbear"}, {"name": "Trello", "type": "trello"}], "flows": ["Airtable → Bannerbear", "Bannerbear → Trello", "On clicking 'execute' → Airtable"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/38/38/385_Send_Airtable_data_as_tasks_to_Trello.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-404", "title": "Notify about Google Sheet changes in Slack and email", "slug": "gh-404-notify-about-google-sheet-changes-in-slack-and-email", "description": "来自 N8N 社区模板库的真实工作流：5 个节点，核心链路 IF → Slack → IF → Send Email。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 5, "nodes": [{"name": "Typeform Trigger", "type": "typeformTrigger"}, {"name": "IF", "type": "if"}, {"name": "Google Sheets", "type": "googleSheets"}, {"name": "Send Email", "type": "emailSend"}, {"name": "Slack", "type": "slack"}], "flows": ["IF → Slack", "IF → Send Email", "Google Sheets → IF", "Typeform Trigger → Google Sheets"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/40/40/404_Notify_about_Google_Sheet_changes_in_Slack_and_email.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-467", "title": "Send sales data from Webhook to Mautic", "slug": "gh-467-send-sales-data-from-webhook-to-mautic", "description": "来自 N8N 社区模板库的真实工作流：17 个节点，核心链路 Webhook → Set Webhook Request → Find User → If not found return -1。", "category": "automation", "categoryLabel": "通用自动化", "nodeCount": 17, "nodes": [{"name": "Webhook", "type": "webhook"}, {"name": "Mautic", "type": "mautic"}, {"name": "Find User", "type": "mautic"}, {"name": "Update User", "type": "mautic"}, {"name": "Tag User", "type": "mautic"}, {"name": "Unsubscribe User", "type": "mautic"}, {"name": "Split Full Name", "type": "function"}, {"name": "If not found return -1", "type": "function"}, {"name": "@MAIN STUDENT DATA", "type": "merge"}, {"name": "Remove unsubscribe", "type": "mautic"}, {"name": "Find User To Tag Sale", "type": "mautic"}, {"name": "Set userFound", "type": "set"}, {"name": "Switch Webhook Types", "type": "switch"}, {"name": "Set Webhook Request", "type": "set"}, {"name": "IF NOT userFound", "type": "if"}, {"name": "Switch User.type", "type": "switch"}, {"name": "IF unsubscribe_from_marketing_emails", "type": "if"}], "flows": ["Webhook → Set Webhook Request", "Find User → If not found return -1", "Update User → IF unsubscribe_from_marketing_emails", "Set userFound → @MAIN STUDENT DATA", "Split Full Name → @MAIN STUDENT DATA", "IF NOT userFound → Mautic", "IF NOT userFound → Switch User.type", "Switch User.type → Update User", "Switch User.type → Unsubscribe User", "Switch User.type → Remove unsubscribe", "@MAIN STUDENT DATA → IF NOT userFound", "Set Webhook Request → Switch Webhook Types", "Switch Webhook Types → Find User", "Switch Webhook Types → Split Full Name", "Switch Webhook Types → Find User To Tag Sale", "Find User To Tag Sale → Tag User", "If not found return -1 → Set userFound", "IF unsubscribe_from_marketing_emails → Unsubscribe User", "IF unsubscribe_from_marketing_emails → Remove unsubscribe"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/46/46/467_Send_sales_data_from_Webhook_to_Mautic.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-471", "title": "Send Github notifications to Discord Webhook", "slug": "gh-471-send-github-notifications-to-discord-webhook", "description": "来自 N8N 社区模板库的真实工作流：6 个节点，核心链路 IF → Discord → Cron → @Get Date 1 min ago。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 6, "nodes": [{"name": "@Get Issue", "type": "httpRequest"}, {"name": "Cron", "type": "cron"}, {"name": "Discord", "type": "discord"}, {"name": "Function", "type": "function"}, {"name": "IF", "type": "if"}, {"name": "@Get Date 1 min ago", "type": "function"}], "flows": ["IF → Discord", "Cron → @Get Date 1 min ago", "Function → IF", "@Get Issue → Function", "@Get Date 1 min ago → @Get Issue"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/47/47/471_Send_Github_notifications_to_Discord_Webhook.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-527", "title": "Receive updates for GitHub events", "slug": "gh-527-receive-updates-for-github-events", "description": "来自 N8N 社区模板库的真实工作流：1 个节点，核心链路 Github Trigger。", "category": "devops", "categoryLabel": "开发运维", "nodeCount": 1, "nodes": [{"name": "Github Trigger", "type": "githubTrigger"}], "flows": [], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/52/52/527_Receive_updates_for_GitHub_events.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-545", "title": "Receive updates for Stripe events", "slug": "gh-545-receive-updates-for-stripe-events", "description": "来自 N8N 社区模板库的真实工作流：1 个节点，核心链路 Stripe Trigger。", "category": "payments", "categoryLabel": "支付事件", "nodeCount": 1, "nodes": [{"name": "Stripe Trigger", "type": "stripeTrigger"}], "flows": [], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/54/54/545_Receive_updates_for_Stripe_events.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
  {"id": "gh-563", "title": "Get contributors information from GitHub in Slack", "slug": "gh-563-get-contributors-information-from-github-in-slack", "description": "来自 N8N 社区模板库的真实工作流：4 个节点，核心链路 GraphQL → Function → Webhook → GraphQL。", "category": "team-chat", "categoryLabel": "团队通知", "nodeCount": 4, "nodes": [{"name": "Webhook", "type": "webhook"}, {"name": "GraphQL", "type": "graphql"}, {"name": "Function", "type": "function"}, {"name": "Slack", "type": "slack"}], "flows": ["GraphQL → Function", "Webhook → GraphQL", "Function → Slack"], "source": {"repo": "zengfr/n8n-workflow-all-templates", "url": "https://github.com/zengfr/n8n-workflow-all-templates/blob/main/n8n-workflow-all-templates/56/56/563_Get_contributors_information_from_GitHub_in_Slack.json", "stars": 110}, "author": {"name": "N8N 社区", "note": "模板收录自开源社区模板库"}, "isFree": true, "updatedAt": "2026-09-07"},
];